=begin
#Catalog API

#This API gets and orders catalog items from different cloud sources.

The version of the OpenAPI document: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ServicePlansApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServicePlansApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ServicePlansApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServicePlansApi' do
    it 'should create an instance of ServicePlansApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ServicePlansApi)
    end
  end

  # unit tests for create_service_plan
  # Create Service Plan
  # Returns the new Service Plan
  # @param [Hash] opts the optional parameters
  # @option opts [ImportServicePlan] :import_service_plan 
  # @return [Array<ServicePlan>]
  describe 'create_service_plan test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_service_plan_modified
  # Patch Service Plan Modified Schema
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @option opts [PatchModifiedServicePlan] :patch_modified_service_plan 
  # @return [DataDrivenFormSchema]
  describe 'patch_service_plan_modified test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_service_plan
  # Show Service Plan
  # Returns the specified Service Plan
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @return [ServicePlan]
  describe 'show_service_plan test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_service_plan_base
  # Show Service Plan Base Schema
  # Returns the specified Service Plan&#39;s base schema
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @return [DataDrivenFormSchema]
  describe 'show_service_plan_base test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_service_plan_modified
  # Show Service Plan modified Schema
  # Returns the specified Service Plan&#39;s modified schema
  # @param id ID of the resource
  # @param [Hash] opts the optional parameters
  # @return [DataDrivenFormSchema]
  describe 'show_service_plan_modified test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
