=begin
#Catalog API

#This API gets and orders catalog items from different cloud sources.

The version of the OpenAPI document: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SettingsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SettingsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SettingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SettingsApi' do
    it 'should create an instance of SettingsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SettingsApi)
    end
  end

  # unit tests for create_setting
  # Create Tenant Setting
  # Create Tenant Setting
  # @param setting Json encoded key/value pair to create a new setting
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'create_setting test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for destroy_setting
  # Delete a Tenant Setting
  # Delete a Tenant Setting
  # @param name name of the setting
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'destroy_setting test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_settings
  # List Tenant Settings
  # List Tenant Settings
  # @param [Hash] opts the optional parameters
  # @return [TenantSettings]
  describe 'list_settings test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_setting
  # Get a specific Tenant Setting
  # Get a specific Tenant Setting
  # @param name name of the setting
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'show_setting test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_setting
  # Update a Tenant Setting
  # Update a Tenant Setting
  # @param name name of the setting
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_setting test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
