=begin
#Catalog API

#This API gets and orders catalog items from different cloud sources.

The version of the OpenAPI document: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::TenantApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TenantApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::TenantApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TenantApi' do
    it 'should create an instance of TenantApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::TenantApi)
    end
  end

  # unit tests for list_tenants
  # List Tenants
  # Get a list of tenants.
  # @param [Hash] opts the optional parameters
  # @return [TenantsCollection]
  describe 'list_tenants test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for show_tenant
  # Get a specific Tenant
  # Gets the tenant specified by the tenant id.
  # @param tenant_id ID of the resource
  # @param [Hash] opts the optional parameters
  # @return [Tenant]
  describe 'show_tenant test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for tenant_seed
  # Seed Tenant Groups
  # Run a task to seed the Tenant Groups required for an org admin to onboard additional users.
  # @param tenant_id ID of the resource
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'tenant_seed test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
