=begin
#Catalog API

#This API gets and orders catalog items from different cloud sources.

The version of the OpenAPI document: 1.0.0
Contact: support@redhat.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.1

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/add_portfolio_item'
require 'openapi_client/models/approval_request'
require 'openapi_client/models/approval_requests_collection'
require 'openapi_client/models/collection_links'
require 'openapi_client/models/collection_metadata'
require 'openapi_client/models/copy_portfolio_item'
require 'openapi_client/models/create_icon'
require 'openapi_client/models/create_portfolio_item'
require 'openapi_client/models/data_driven_form_schema'
require 'openapi_client/models/graph_ql_request'
require 'openapi_client/models/graph_ql_response'
require 'openapi_client/models/icon'
require 'openapi_client/models/import_service_plan'
require 'openapi_client/models/order'
require 'openapi_client/models/order_item'
require 'openapi_client/models/order_items_collection'
require 'openapi_client/models/orders_collection'
require 'openapi_client/models/patch_modified_service_plan'
require 'openapi_client/models/portfolio'
require 'openapi_client/models/portfolio_item'
require 'openapi_client/models/portfolio_item_next_name'
require 'openapi_client/models/portfolio_items_collection'
require 'openapi_client/models/portfolios_collection'
require 'openapi_client/models/progress_message'
require 'openapi_client/models/progress_messages_collection'
require 'openapi_client/models/restore_key'
require 'openapi_client/models/service_plan'
require 'openapi_client/models/setting'
require 'openapi_client/models/share_info'
require 'openapi_client/models/share_policy'
require 'openapi_client/models/tag'
require 'openapi_client/models/tag_item'
require 'openapi_client/models/tags_collection'
require 'openapi_client/models/tenant'
require 'openapi_client/models/tenant_settings'
require 'openapi_client/models/tenants_collection'
require 'openapi_client/models/unshare_policy'

# APIs
require 'openapi_client/api/default_api'
require 'openapi_client/api/icon_api'
require 'openapi_client/api/order_api'
require 'openapi_client/api/order_item_api'
require 'openapi_client/api/portfolio_api'
require 'openapi_client/api/portfolio_item_api'
require 'openapi_client/api/service_plans_api'
require 'openapi_client/api/settings_api'
require 'openapi_client/api/tags_api'
require 'openapi_client/api/tenant_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
